// Use this file as a template for a Job definition using Job DSL Jenkins Plugin https://plugins.jenkins.io/job-dsl/
def generatedBy = "Generated by jenkins.groovy at ${new Date()}"
def organization = "yourorg"
def project = "yourapp"

// You need to have a MacOS machine configured in your Nodes in Jenkins with this label
def machineLabel = "macosx"

def yourKeychainPassword = "yourpass"

def gitProjectUrl = "git@github.com:${organization}/${project}.git"
def branchName = "main"

def channel = "#${project}-alerts"

job("build-native") {
  label(machineLabel)
  description generatedBy
  scm {
    git(gitProjectUrl, branchName)
  }
  triggers {
    scm(trigger)
  }
  steps {
    shell("""
      ${installYarn}
      cd private/native-app/${environment}
      APP_ID=com.meteorapp.mobile ./build.sh
      APP_ID=com.meteorapp.mobile ./publish-android.sh
      FL_UNLOCK_KEYCHAIN_PASSWORD=${yourKeychainPassword} ./publish-ios.sh
    """)
  }
  configure {
    it / 'publishers' / 'jenkins.plugins.slack.SlackNotifier'(plugin: "slack@2.3") {
      room(channel)
      notifySuccess(true)
      notifyFailure(true)
      notifyBackToNormal(true)
      notifyRepeatedFailure(true)
    }
  }
}
